### ISSUE TITLE
Xcode12.5，文件类中参数错误提示，导致本库无法安装

### ISSUE THREAD

**Issue by UniqueSilence** [facebook/FBRetainCycleDetector#119] opened 2021-05-28 02:29 UTC
在12.5版本的Xcode中  /FBRetainCycleDetector/Layout/Classes/FBClassStrongLayout.mm文件类中，202行，
layoutCache[currentClass] = ivars;  会报关于currentClass作为参数的错误提示如下：

Cannot initialize a parameter of type 'id<NSCopying> _Nonnull' with an rvalue of type 'Class'。

在12.4版本的XCode中，安装时没有这个问题的。

**Comment by XDChang** [comment] 2021-05-31 01:19
我也遇到了，期待解决方案。

**Comment by youngdfb** [comment] 2021-06-01 18:29
This looks like a duplicate of an issue that has been reported, such as in https://github.com/facebook/FBRetainCycleDetector/issues/115.  Fellow users have given a work around until we have the opportunity to update the cocoa pods to latest code (which has the fix).

**Closed by youngdfb** 2021-06-01 18:29 UTC
